OTS/urls.py
from django.urls import path
from OTS.views import *
app_name = 'OTS'
urlpatterns = [
    path('',welcome),
    path('new-candidate',candidateRegistrationForm,name = 'registrationForm'),
    path('store-candidate',candidateRegistration,name = 'storeCandidate'),
    path('login',loginView,name = 'login'),
    path('home',candidateHome,name='home'),
    path('test-paper',testPaper,name='testPaper'),
    path('calculate-result',calculateTestResult,name = 'calculateTest'),
    path('test-history',testResultHistory,name = 'testHistory'),
    path('result',showTestResult,name='result'),
    path('logout',logoutView,name='logout'),

]

testingsystem/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('OTS/',include('OTS.urls')),
    path('',include('OTS.urls')),

]

OTS/models.py
from django.db import models

# Create your models here.

class Candidate(models.Model):
    username = models.CharField(primary_key=True,max_length=20)
    password = models.CharField(null=False,max_length=20)
    name = models.CharField(null=False,max_length=30)
    test_attempted = models.IntegerField(default=0)
    points = models.FloatField(default=0.0)

class Question(models.Model):
    qid = models.IntegerField(primary_key=True,auto_created=True)
    que = models.TextField()
    a = models.CharField(max_length=255)
    b = models.CharField(max_length=255)
    c = models.CharField(max_length=255)
    d = models.CharField(max_length=255)
    ans = models.CharField(max_length=255)

class Result(models.Model):
    resultid = models.BigAutoField(primary_key=True,auto_created=True)
    username = models.ForeignKey(Candidate,on_delete=models.CASCADE)
    date = models.DateField(auto_now=True)
    time = models.TimeField(auto_now=True)
    attempt = models.IntegerField()
    right = models.IntegerField()
    wrong = models.IntegerField()
    points = models.FloatField()

OTS/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse,HttpResponseRedirect
from OTS.models import *
import random

# Create your views here.

def welcome(request):
    template = loader.get_template('welcome.html')
    return HttpResponse(template.render())

def candidateRegistrationForm(request):
    return render(request,'registration_form.html')

def candidateRegistration(request):
    if request.method=='POST':
        username = request.POST['username']
        #check if the user already exits.
        if len(Candidate.objects.filter(username=username)):
            userStatus=1
        else:
            candidate = Candidate()
            candidate.username = username
            candidate.password = request.POST['password']
            candidate.name = request.POST['name']
            candidate.save()
            userStatus=2
    else:
        userStatus=3 #request method is not post
    context={
        'userStatus':userStatus
    }
    return render(request,'registration.html',context)

def loginView(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        candidate = Candidate.objects.filter(username=username,password=password)
        if len(candidate)==0:
            loginError="Invalid Username or Password"
            res = render(request,'login.html',{'loginError':loginError})
        else:
            # login success
            # session variable , server me bnte hai,
            request.session['username']=candidate[0].username # username is stored in session variable
            request.session['name']=candidate[0].name
            res = HttpResponseRedirect('home') 
    else:
        res = render(request,'login.html')
    return res

def candidateHome(request):
    if 'name' not in request.session.keys():
        res = HttpResponseRedirect('login')
    else:
        res = render(request,'home.html')
    return res

def testPaper(request):
    if 'name' not in request.session.keys():
        res = HttpResponseRedirect('login')
    #fetch question paper from database table
    n = int(request.GET['n'])
    question_pool = list(Question.objects.all())
    random.shuffle(question_pool)
    questions_list=question_pool[:n]
    context = {
        'questions':questions_list
    }
    res = render(request,'testpaper.html',context)
    return res
def calculateTestResult(request):
    if 'name' not in request.session.keys():
        res = HttpResponseRedirect('login')
    total_attempt=0
    total_right=0
    total_wrong=0
    qid_list=[]
    for k in request.POST:
        if k.startswith('qno'):
            qid_list.append(int(request.POST[k]))
    for n in qid_list:
        question=Question.objects.get(qid=n)  # get return single object 
        try:
            if question.ans == request.POST['q'+str(n)]:
                total_right+=1
            else:
                total_wrong+=1
            total_attempt+=1
        except:
            pass
    #calculation points
    points=(total_right-total_wrong)/len(qid_list)*10
    #store result in Result table
    result=Result()
    result.username = Candidate.objects.get(username=request.session['username'])#need to assing object in foreign key
    result.attempt=total_attempt
    result.right=total_right
    result.wrong = total_wrong
    result.points=points 
    result.save()

    #update candidate table
    candidate=Candidate.objects.get(username=request.session['username'])
    candidate.test_attempted+=1
    candidate.points=(candidate.points*(candidate.test_attempted-1)+points)/candidate.test_attempted
    candidate.save()
    return HttpResponseRedirect('result')
def testResultHistory(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")

    candidate=Candidate.objects.filter(username=request.session['username'])
    results=Result.objects.filter(username_id=candidate[0].username)
    context={'candidate':candidate[0],'results':results}
    res=render(request,'candidate_history.html',context)
    return res
def showTestResult(request):
    if 'name' not in request.session.keys():
        res = HttpResponseRedirect('login')
    result=Result.objects.filter(resultid=Result.objects.latest('resultid').resultid,username_id=request.session['username'])
    context={
        'result':result
    }
    res = render(request,'show_result.html',context)
    return res
def logoutView(request):
    if 'name' in request.session.keys():
        del request.session['username']
        del request.session['name']
    res = HttpResponseRedirect('login')
    return res

OTS/templates/candidate_history.html
{% extends 'main.html' %}

{% block title %} OTS - Candidate Result History {% endblock %}

{% block top %}
    <div class="d-flex justify-content-between align-items-center">
        <a href="{% url 'OTS:home' %}" class="btn btn-secondary">Home</a>
        <a href="{% url 'OTS:logout' %}" class="btn btn-danger">Logout</a>
    </div>
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Your Report Card</h1>
        <p>Hi <span class="text-primary">{{candidate.name}}</span>, 
            you have attempted a total of <span class="text-primary">{{candidate.test_attempted}}</span> tests.
        </p>
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead class="thead-dark text-center">
                    <tr>
                        <th>Date</th>
                        <th>Time</th>
                        <th>Attempt</th>
                        <th>Right</th>
                        <th>Wrong</th>
                        <th>Points</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    {% for r in results %}
                    <tr>
                        <td style="height: 50px;">{{r.date}}</td>
                        <td style="height: 50px;">{{r.time}}</td>
                        <td style="height: 50px;">{{r.attempt}}</td>
                        <td style="height: 50px;">{{r.right}}</td>
                        <td style="height: 50px;">{{r.wrong}}</td>
                        <td style="height: 50px;">{{r.points}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

OTS/templates/home.html
{% extends 'main.html' %}

{% block title %} OTS - Candidate Home{% endblock %}

{% block top %}
    <a class="btn btn-secondary" href="{% url 'OTS:home' %}">Home</a>
    <a class="btn btn-danger" href="{% url 'OTS:logout' %}">Logout</a>
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Welcome {{ request.session.name }}, to your home page</h1>

        <div class="row">
            <div class="col-md-8">
                <div class="test-paper-section">
                    <h2>Test Paper Section</h2>
                    <div class="button-link">
                        <a href="{% url 'OTS:testPaper' %}?n=1">Test of 1 Question</a>
                    </div>
                    <div class="button-link">
                        <a href="{% url 'OTS:testPaper' %}?n=3">Test of 3 Questions</a>
                    </div>
                    <div class="button-link">
                        <a href="{% url 'OTS:testPaper' %}?n=5">Test of 5 Questions</a>
                    </div>
                    <div class="button-link">
                        <a href="{% url 'OTS:testPaper' %}?n=10">Test of 10 Questions</a>
                    </div>
                    <div class="button-link">
                        <a href="{% url 'OTS:testPaper' %}?n=15">Test of 15 Questions</a>
                    </div>
                    <div class="button-link">
                        <a href="{% url 'OTS:testPaper' %}?n=20">Test of 20 Questions</a>
                    </div>
                    <div class="button-link">
                        <a href="{% url 'OTS:testPaper' %}?n=25">Test of 25 Questions</a>
                    </div>
                    <div class="button-link">
                        <a href="{% url 'OTS:testPaper' %}?n=30">Test of 30 Questions</a>
                    </div>
                </div>
            </div>

            <div class="col-md-4 ">
                <div class="card test-result-section sticky-top result-padding">
                    <div class="card-body">
                        <h2 class="card-title">Test Result Section</h2>
                        <div class="button-link d-flex align-items-center justify-content-center">
                            <a href="{% url 'OTS:testHistory' %}?n=1">Test History</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

OTS/templates/login.html
{% extends 'main.html' %}

{% block title %} OTS - Login {% endblock %}

{% block top %}
    <a class="btn btn-secondary" style="color: white;" href="{% url 'OTS:registrationForm' %}">Signup</a>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-dark text-white">Login</div>
                    <div class="card-body">
                        {% if loginError %}
                            <div class="alert alert-danger" role="alert">
                                {{ loginError }}
                            </div>
                        {% endif %}
                        <form action="{% url 'OTS:login' %}" method="POST" class="needs-validation" novalidate>
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="username" class="form-label">Username</label>
                                <input type="text" name="username" class="form-control" required>
                                <div class="invalid-feedback">Please enter your username.</div>
                            </div>
                            <div class="mb-3">
                                <label for="password" class="form-label">Password</label>
                                <input type="password" name="password" class="form-control" required>
                                <div class="invalid-feedback">Please enter your password.</div>
                            </div>
                            <div class="mb-3">
                                <button type="submit" class="btn btn-primary">Login</button>
                                <button type="reset" class="btn btn-secondary">Clear</button>
                            </div>
                        </form>
                        <p>New User? <a href="{% url 'OTS:registrationForm' %}">Click Here</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

OTS/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Online Testing System{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'theme.css' %}">
    <link rel="stylesheet" href="{% static 'buttonstyle.css' %}">
    <link rel="stylesheet" href="{% static 'custom.css' %}">
</head>
<body class="bg-light d-flex flex-column min-vh-100">
    <header class="bg-dark text-white py-1">
        <div class="container text-center d-flex flex-direction-row justify-content-between align-items-center">
            <h1 id="heading" class="display-4">Online Testing System</h1>
            <nav class="nav justify-content-center">
                {% block top %}{% endblock %}
            </nav>
        </div>
    </header>
    <main class="container my-5 p-4 bg-white rounded shadow-sm flex-grow-1">
        {% block content %}{% endblock %}
    </main>
    <footer class="bg-dark text-white text-center py-3">
        <div class="container">
            <p class="mb-0">&copy; 2024 Online Testing System. All rights reserved.</p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

OTS/templates/registration.html
{% extends 'main.html' %}

{% block title %} OTS-Registration Status {% endblock %}

{% block top %}
    <div class="d-flex justify-content-end mb-4">
        <a href="{% url 'OTS:registrationForm' %}" class="btn btn-primary me-2">Signup</a>
        <a href="{% url 'OTS:login' %}" class="btn btn-secondary">Login</a>
    </div>
{% endblock %}

{% block content %}
    <div class="container mt-5">
        {% if userStatus == 1 %}
            <div class="alert alert-warning text-center">
                <h4>Sorry, Username already exists</h4>
                <p>Please try with a different username.</p>
                <a href="{% url 'OTS:registrationForm' %}" class="btn btn-warning mt-3">Back to Candidate Registration Form</a>
            </div>
        {% elif userStatus == 2 %}
            <div class="alert alert-success text-center">
                <h4>Congratulations!</h4>
                <p>User created successfully.</p>
                <a href="{% url 'OTS:login' %}" class="btn btn-success mt-3">Login</a>
            </div>
        {% elif userStatus == 3 %}
            <div class="alert alert-danger text-center">
                <h4>Oops! Improper Request</h4>
                <p>Sorry, Username already exists, please try with a different username.</p>
                <a href="{% url 'OTS:registrationForm' %}" class="btn btn-danger mt-3">Back to Candidate Registration Form</a>
            </div>
        {% endif %}
    </div>
{% endblock %}

OTS/templates/registration_form.html
{% extends 'main.html' %}

{% block title %} Welcome to Online Testing System {% endblock %}

{% block top %}
    <a class="btn btn-danger" href="{% url 'OTS:login' %}">Login</a>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-dark text-white">Register</div>

                    <div class="card-body">
                        <form action="{% url 'OTS:storeCandidate' %}" method="POST" class="needs-validation" novalidate>
                            {% csrf_token %}

                            <div class="mb-3">
                                <label for="username" class="form-label">Username</label>
                                <input type="text" name="username" class="form-control" required>
                                <div class="invalid-feedback">Please provide a username.</div>
                            </div>

                            <div class="mb-3">
                                <label for="password" class="form-label">Password</label>
                                <input type="password" name="password" class="form-control" required>
                                <div class="invalid-feedback">Please provide a password.</div>
                            </div>
                            
                            <div class="mb-3">
                                <label for="name" class="form-label">Name</label>
                                <input type="text" name="name" class="form-control" required>
                                <div class="invalid-feedback">Please provide your name.</div>
                            </div>

                            <button type="submit" class="btn btn-primary">Submit</button>
                            <button type="reset" class="btn btn-secondary">Clear</button>
                        </form>
                    </div>
                </div>
                <p class="mt-3">Already have an account? <a href="{% url 'OTS:login' %}">Login here</a>.</p>
            </div>
        </div>
    </div>
{% endblock %}

OTS/templates/show_result.html
{% extends 'main.html' %}

{% block title %} OTS-Test Result {% endblock %}

{% block top %}
    <div class="d-flex justify-content-between align-items-center">
        <a href="{% url 'OTS:home' %}" class="btn btn-secondary">Home</a>
        <a href="{% url 'OTS:logout' %}" class="btn btn-danger">Logout</a>
    </div>
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Test Results</h1>
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th class="text-center" style="height: 60px;">Date</th>
                        <th class="text-center" style="height: 60px;">Time</th>
                        <th class="text-center" style="height: 60px;">Attempt</th>
                        <th class="text-center" style="height: 60px;">Right</th>
                        <th class="text-center" style="height: 60px;">Wrong</th>
                        <th class="text-center" style="height: 60px;">Points</th>
                    </tr>
                </thead>
                <tbody>
                    {% for r in result %}
                    <tr>
                        <td class="text-center">{{r.date}}</td>
                        <td class="text-center">{{r.time}}</td>
                        <td class="text-center">{{r.attempt}}</td>
                        <td class="text-center">{{r.right}}</td>
                        <td class="text-center">{{r.wrong}}</td>
                        <td class="text-center">{{r.points}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

OTS/templates/testpaper.html
{% extends 'main.html' %}

{% block title %} OTS-Test Paper {% endblock %}

{% block top %}
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4 text-center">OTS Test Paper</h1>
        <form action="{% url 'OTS:calculateTest' %}" method="POST">
            {% csrf_token %}
            {% for question in questions %}
            <div class="mb-4 p-4 border rounded shadow-sm">
                <input type="hidden" name="qno{{question.qid}}" value="{{question.qid}}">
                <div class="mb-3">
                    <strong>{{ forloop.counter }}. {{ question.que }}</strong>
                </div>
                <div class="form-check mb-2">
                    <input class="form-check-input" type="radio" name="q{{question.qid}}" id="q{{question.qid}}a" value="a">
                    <label class="form-check-label" for="q{{question.qid}}a">
                        {{question.a}}
                    </label>
                </div>
                <div class="form-check mb-2">
                    <input class="form-check-input" type="radio" name="q{{question.qid}}" id="q{{question.qid}}b" value="b">
                    <label class="form-check-label" for="q{{question.qid}}b">
                        {{question.b}}
                    </label>
                </div>
                <div class="form-check mb-2">
                    <input class="form-check-input" type="radio" name="q{{question.qid}}" id="q{{question.qid}}c" value="c">
                    <label class="form-check-label" for="q{{question.qid}}c">
                        {{question.c}}
                    </label>
                </div>
                <div class="form-check mb-2">
                    <input class="form-check-input" type="radio" name="q{{question.qid}}" id="q{{question.qid}}d" value="d">
                    <label class="form-check-label" for="q{{question.qid}}d">
                        {{question.d}}
                    </label>
                </div>
            </div>
            {% endfor %}
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}

OTS/templates/welcome.html
{% extends 'main.html' %}

{% block title %} Welcome to Online Testing System {% endblock %}

{% block top %}
    <div class="btn-group" role="group">
        <a class="btn btn-secondary" href="{% url 'OTS:registrationForm' %}">Signup</a>
        <a class="btn btn-danger" href="{% url 'OTS:login' %}">Login</a>
    </div>
{% endblock %}

{% block content %}
    <div class="container-fluid bg-gradient ">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header bg-dark text-white">{{ block.super }}</div>

                    <div class="card-body">
                        <h2 class="text-center mb-4">Welcome to Online Testing System</h2>
                        <p class="text-center mb-4 lead">Empower your learning with our innovative online testing platform. Experience a seamless and efficient way to assess your knowledge and skills.</p>
                        <div class="btn-group d-flex justify-content-center mt-3" role="group">
                            <a class="btn btn-lg btn-success me-3" href="{% url 'OTS:registrationForm' %}">Signup</a>
                            <span class="text-muted align-self-center fw-bold">or</span>
                            <a class="btn btn-lg btn-danger ms-3" href="{% url 'OTS:login' %}">Login</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}